### ISSUE TITLE
Adding support for future/promises

### ISSUE THREAD

**Issue by PabloReszczynski** [gerritjvv/fmap-clojure#1]
I'm having issues using this library to fmap over a Future object.
```clojure
(extend-protocol Functor
  <some.future.class>
  (fmap [v f] (future (f (deref v))))
  (lift [v] (deref v)))

(>>=* (future 5) :lift) ; => 5
(>>=* (future 5) inc) ; Raises exception: clojure.core$future_call$reify__6962 cannot be cast to java.lang.Number
; The above example should return a Future object with val = 6
```

**Comment by gerritjvv** [comment]
hi, I'm currently on holidays, will only be able to look at this next week. 
if you want to debug this in the meantime add some print statements to you're extend functor functions to make sure they are being callled and what is the type of the value they pass to fmap's function argument.

**Comment by PabloReszczynski** [comment]
All right. It isn't printing anything, so my bet is that I'm giving the class wrong.
I cannot tell what is the class or type of Clojure's futures, since when I do `(type (future 5))` it prints `clojure.core$future_call$reify__6962`, and I don't know what that means.
For the time being I'm going to use [Imminent](https://github.com/leonardoborges/imminent), which has already implemented chainable futures and promises.

**Comment by gerritjvv** [comment]
Imminent is maybe a better choice for what you want if you're just using futures.

For reference java future implements: java.util.concurrent.Future

```
user=> (import '(java.util.concurrent Future))
java.util.concurrent.Future
user=> (instance? Future (future))
true
```
